/*
 * @Author: yh
 * @Date: 2022/10/24 23:43
 * @Description: 
 * @FilePath: workPrinciple.h
 */

#ifndef CESSENCE_OBJECTORIENTEDPROGRAM_OBJECT_ORIENTED_VIRTUAL_VIRTUALTABLEWORKINGPRINCIPLE_WORKPRINCIPLE_H
#define CESSENCE_OBJECTORIENTEDPROGRAM_OBJECT_ORIENTED_VIRTUAL_VIRTUALTABLEWORKINGPRINCIPLE_WORKPRINCIPLE_H

#endif //CESSENCE_OBJECTORIENTEDPROGRAM_OBJECT_ORIENTED_VIRTUAL_VIRTUALTABLEWORKINGPRINCIPLE_WORKPRINCIPLE_H
