/*
 * @Author: yh
 * @Date: 2022/9/12 19:15
 * @Description: 
 * @FilePath: moveObject.h
 */

#ifndef CESSENCE_OBJECTORIENTEDPROGRAM_OBJECT_ORIENTED_MOVEOBJECT_MOVEOBJECT_H
#define CESSENCE_OBJECTORIENTEDPROGRAM_OBJECT_ORIENTED_MOVEOBJECT_MOVEOBJECT_H

#endif //CESSENCE_OBJECTORIENTEDPROGRAM_OBJECT_ORIENTED_MOVEOBJECT_MOVEOBJECT_H
